### ISSUE TITLE
Annuaire RGE: le numéro de téléphone n'est plus affiché dans la fiche artisan

### ISSUE THREAD

**Issue by pboko** [vteco/general#6]
Bug de script Optelo, qui est appelé deux fois. 
Le tel est affiché dans la popup de la carte, ce qui nous convenait lorsque la carte était en haut de page.

**Comment by pboko** [comment]
Autre solution recommandée par Optelo:

Vous devez aller sur cette adresse : http://www.audiotel.me/
Adresse email : rotonum@optelo.com
Mot de passe : rotonum

**Comment by JonathanVTE** [comment]
Solution : supprimer le tel de la pop up

**Comment by lindavte** [comment]
svn 8372
