### ISSUE TITLE
Annuaire RGE: les logs d'erreurs font saturer le disque dur serveur

### ISSUE THREAD

**Issue by pboko** [vteco/general#8]
C'est toujours la même erreur, qui n'a pas d'impact graphique sur le site, et qui concerne une classe WpLatte.

Il faut repérer ce qui provoque ces entrées dans le log d'erreur, et faire en sorte que l'entrée ne soit plus loggée.

**Comment by pboko** [comment]
Quelques exemples:
[Sun Jan 11 12:03:44.918677 2015] [:error] [pid 31739] [client 90.63.13.32:52416] PHP Fatal error:  Class 'WpLatte' not found in /var/www/vte/annuaire/wp-content/themes/directory/index.php on line 43, referer: http://www.annuaireartisanrge.fr/?s=&geo-radius=100&geo-lat=0&geo-lng=0&categories=73&locations=97&dir-search=yes
[Sun Jan 11 14:54:47.117379 2015] [:error] [pid 32016] [client 171.6.247.138:47572] PHP Fatal error:  Class 'WpLatte' not found in /var/www/vte/annuaire/wp-content/themes/directory/index.php on line 43, referer: http://www.annuaireartisanrge.fr/artisan/74-haute-savoie_passy_amt-plomberie_80-rue-des-egratz_797726692/
[Mon Jan 12 10:21:48.252102 2015] [:error] [pid 5816] [client 80.9.34.24:51544] PHP Fatal error:  Class 'WpLatte' not found in /var/www/vte/annuaire/wp-content/themes/directory/index.php on line 43, referer: http://www.annuaireartisanrge.fr/artisan/07-ardeche_aubignas_dominique-labeille-et-fils_quartier-saint-philippe_791156912/

**Comment by lindavte** [comment]
svn 8363
A vérifier lundi si ça fonction

**Comment by lindavte** [comment]
svn 8365, 8366

**Comment by lindavte** [comment]
svn 8370
